Robustness: Ensure that --transacted-file|-f is passed

diff --git a/bin/withTransaction b/bin/withTransaction
--- a/bin/withTransaction
+++ b/bin/withTransaction
@@ -176,7 +176,12 @@ case "$action" in
 		commands=("${simpleCommand[@]}")
 	    fi
 	fi
-	if [ ${#commands[@]} -eq 0 ]; then
+	if [ -z "$transactedFilespec" ]; then
+	    echo 'ERROR: Missing -f|--transacted-file FILE.'
+	    echo
+	    printShortUsage "$0"
+	    exit 2
+	elif [ ${#commands[@]} -eq 0 ]; then
 	    echo 'ERROR: No COMMAND(s) specified; need to pass -c|--command "COMMANDLINE", or SIMPLECOMMAND.'
 	    echo
 	    printUsage "$0"
