withTransaction: FIX: Remove duplicate printUsage(), correct usage functions used

diff --git a/bin/withTransaction b/bin/withTransaction
--- a/bin/withTransaction
+++ b/bin/withTransaction
@@ -91,15 +91,6 @@ HELPTEXT
     printf '%q %s\n' "$(basename "$1")" '--foo bar /tmp/foobar'
 }
 
-printUsage()
-{
-    cat <<HELPTEXT
-Execute COMMAND ...
-HELPTEXT
-    echo
-    printf 'Usage: %q %s\n' "$(basename "$1")" '-c|--command "COMMANDLINE" [-c ...] | [--] SIMPLECOMMAND [...] [-?|-h|--help]'
-}
-
 transactedFilespec=
 lockFilespec=
 mode=write
@@ -115,7 +106,7 @@ typeset -a commands=()
 while [ $# -ne 0 ]
 do
     case "$1" in
-	--help|-h|-\?)	shift; printShortUsage "$0"; exit 0;;
+	--help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
 	--transacted-file|-f)
 			shift; transactedFilespec="$1"; shift;;
 	--lock-file|-l)	shift; lockFilespec="$1"; shift;;
@@ -132,7 +123,7 @@ do
 			shift; dropArguments+=("$1"); shift;;
 	--command|-c)	shift; commands+=(${commands:+;} "$1"); isNeedEval=t; shift;;
 	--)		shift; break;;
-	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printShortUsage "$0"; } >&2; exit 2;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)		break;;
     esac
 done
@@ -160,17 +151,17 @@ fi
 if [ ${#commands[@]} -eq 0 ]; then
     echo 'ERROR: No COMMAND(s) specified; need to pass -c|--command "COMMANDLINE", or SIMPLECOMMAND.'
     echo
-    printShortUsage "$0"
+    printUsage "$0"
     exit 2
 elif [ "$isRollbackOnFailure" ] && [ "$mode" = read ]; then
     echo 'ERROR: Cannot combine --rollback-on-failure with -r|--read-only.'
     echo
-    printShortUsage "$0"
+    printUsage "$0"
     exit 2
 elif [ "${transactionOwner:0:1}" = '*' ]; then
     echo >&2 'ERROR: OWNER-ID must not start with *.'
     echo >&2
-    printShortUsage "$0" >&2
+    printUsage "$0" >&2
     exit 2
 fi >&2
 
